### PR TITLE
Update _common.sh

### PR DESCRIPTION
**Pull request by mehighlow**
replace a set of commands and variables with a build-in bash RANDOM variable. Works both for Linux and MacOS(bash or zsh)

### CODE REVIEW

**Comment by mehighlow** [comment]
@DariuszPorowski PTAL

**Review by DariuszPorowski — COMMENTED** [review]
hmmm but ${RANDOM:0:5} not always return 5 digits. I wonder if this could be a name conflict problem...

**Comment by mehighlow** [comment]
> hmmm but ${RANDOM:0:5} not always return 5 digits. I wonder if this could be a name conflict problem...

Fair point.
I've replaced ${RANDOM:0:5} which not always gives 5 digits with a workaround of adding 10000. $RANDOM returns a different random integer(range: 0 - 32767, signed 16-bit integer) at each invocation.

@DariuszPorowski , PTAL and merge if it looks good to you. ty

**Comment by DariuszPorowski** [comment]
@mehighlow actuali UNIQUER var is used in soe script so, we cannot remove this variable. Its part of get_unique_name function but variable is global not local and its ussed in some cased under ADO deployment script.

**Comment by DariuszPorowski** [comment]
@mehighlow actuali UNIQUER var is used in soe script so, we cannot remove this variable. Its part of get_unique_name function but variable is global not local and its ussed in some cased under ADO deployment script.

**Pull request closed without merging**
